# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import time
import socket
from PyQt5.QtCore import pyqtSignal, QThread
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 958)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 35, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 35, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 35, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 35, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 10, 171, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 110, 891, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 290, 891, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 311, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(330, 140, 20, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.cam_ip_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.cam_ip_edit.setGeometry(QtCore.QRect(130, 180, 181, 31))
        self.cam_ip_edit.setStyleSheet("border-radius: 10px;\n"
"background-color: #43455b;\n"
"padding: 5px;\n"
"color: #c3c1c5;\n"
"font-size: 13px;")
        self.cam_ip_edit.setObjectName("cam_ip_edit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.cam_connect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cam_connect_btn.setGeometry(QtCore.QRect(90, 230, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cam_connect_btn.setFont(font)
        self.cam_connect_btn.setStyleSheet("color:#004cf5;\n"
"background-color:#1f1e2b;\n"
"border-radius: 15px;")
        self.cam_connect_btn.setObjectName("cam_connect_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 120, 311, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 220, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 260, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setObjectName("label_7")
        self.uname_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.uname_edit.setGeometry(QtCore.QRect(470, 170, 181, 31))
        self.uname_edit.setStyleSheet("border-radius: 10px;\n"
"background-color: #43455b;\n"
"padding: 5px;\n"
"color: #c3c1c5;\n"
"font-size: 13px;")
        self.uname_edit.setObjectName("uname_edit")
        self.server_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.server_edit.setGeometry(QtCore.QRect(470, 210, 181, 31))
        self.server_edit.setStyleSheet("border-radius: 10px;\n"
"background-color: #43455b;\n"
"padding: 5px;\n"
"color: #c3c1c5;\n"
"font-size: 13px;")
        self.server_edit.setObjectName("server_edit")
        self.port_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.port_edit.setGeometry(QtCore.QRect(470, 250, 181, 31))
        self.port_edit.setStyleSheet("border-radius: 10px;\n"
"background-color: #43455b;\n"
"padding: 5px;\n"
"color: #c3c1c5;\n"
"font-size: 13px;")
        self.port_edit.setObjectName("port_edit")
        self.join_btn = QtWidgets.QPushButton(self.centralwidget)
        self.join_btn.setGeometry(QtCore.QRect(700, 150, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.join_btn.setFont(font)
        self.join_btn.setStyleSheet("color:#004cf5;\n"
"background-color:#1f1e2b;\n"
"border-radius: 15px;")
        self.join_btn.setObjectName("join_btn")
        self.ai_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ai_btn.setGeometry(QtCore.QRect(700, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ai_btn.setFont(font)
        self.ai_btn.setStyleSheet("color:#004cf5;\n"
"background-color:#1f1e2b;\n"
"border-radius: 15px;")
        self.ai_btn.setObjectName("ai_btn")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(750, 200, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 80, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setObjectName("label_9")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setEnabled(True)
        self.camera_label.setGeometry(QtCore.QRect(20, 330, 900, 500))
        self.camera_label.setObjectName("camera_label")
        self.system_stat_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.system_stat_edit.setGeometry(QtCore.QRect(10, 870, 911, 51))
        self.system_stat_edit.setStyleSheet("border-radius: 10px;\n"
"background-color: #43455b;\n"
"padding: 5px;\n"
"color: #c3c1c5;\n"
"font-size: 13px;")
        self.system_stat_edit.setReadOnly(True)
        self.system_stat_edit.setObjectName("system_stat_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TicTacToe"))
        self.label.setText(_translate("MainWindow", "X O"))
        self.label_2.setText(_translate("MainWindow", "Step - 1 : Connect to Camera"))
        self.label_4.setText(_translate("MainWindow", "Camera IP"))
        self.cam_connect_btn.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "Step - 2 : Connect to a Player"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.label_6.setText(_translate("MainWindow", "Server"))
        self.label_7.setText(_translate("MainWindow", "Port"))
        self.join_btn.setText(_translate("MainWindow", "Join"))
        self.ai_btn.setText(_translate("MainWindow", "Play With AI"))
        self.label_8.setText(_translate("MainWindow", "or"))
        self.label_9.setText(_translate("MainWindow", "An AR Tic Tac Toe Game"))
        self.camera_label.setText(_translate("MainWindow", "Camera Space"))